# action.yml
name: "Secrets Sync Action"
description: "Copies secrets from the action's environment to many other repos."
inputs:
  github_token:
    description: "Token to use to get repos and write secrets"
    required: true
  repositories:
    description: |
      New line deliminated regex expressions to select repositories. 
      Repositires are limited to those in whcich the token user is an owner 
      or collaborator.
    required: true
  secrets:
    description: |
      New line deliminated regex expressions to select values from `process.env`. 
      Use the action env to pass secrets from the repository in which this action 
      runs with the `env` attribute of the step.
    required: true
  dry_run:
    description: |
      Run everything except for secret create and update functionality.
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
